### ISSUE TITLE
Implement new core classes

### ISSUE THREAD

**Issue by gustavolgcr** [InsightLab/graphast#42]
Implement the newly defined core classes (Node, Edge, and Graph).

**Comment by gustavolgcr** [comment]
Follow the Diagram described here: https://drive.google.com/open?id=0B_GzZsWBdMSpejlYVVg1a3hrUms

**Comment by archangel777** [comment]
Done!
The problem is, this issue can't be closed by commit messages, since we're working on another branch (Core-Refactoring) and will only be able merge to the default branch (Master) once everything is done.

**Comment by gustavolgcr** [comment]
I think that there's no problem of closing it manually.
