### ISSUE TITLE
Update functions that handle I / O of the graph to receive a File

### ISSUE THREAD

**Issue by araujodavid** [InsightLab/graphast#45]
StorageUtils.deleteMMapGraph
MMapGraphStructure
GraphStorage.loadGraph
GraphStorage.saveGraph
RandomGraphGenerator.generateRandomMMapGraph

**Comment by araujodavid** [comment]
@archangel777 lembra de remover as redundâncias dos métodos que usam a substring "graph" (i.e.: loadGraph, saveGraph, ...)

**Comment by archangel777** [comment]
Davi, pelos testes que estava fazendo, parece ser mais cômodo passar uma string "path/to/graph" do que passar um file, até porque consigo tratar algumas coisas como não colocar a ultima "/" de um diretório dentro das funções que usam, além de fazer com q o usuário não precise se preocupar com mais 1 instanciação de objeto.

**Comment by araujodavid** [comment]
It is fine as long as you perform all the validation checks of this String within the methods. @archangel777
